Add MergeTags in Link component attribute
zalify/easy-email-editor pull request #390
Opened 2024-04-17 08:41 UTC by alexmateos

Created this PR to add merge tags in Link component attribute and fix this issue: https://github.com/zalify/easy-email-editor/issues/195

Before:

<img width="351" alt="image" src="https://github.com/zalify/easy-email-editor/assets/5480073/e2883730-a5ca-4dc4-92c6-bb909e40c563">

After:

<img width="350" alt="image" src="https://github.com/zalify/easy-email-editor/assets/5480073/ee403109-e19d-4b35-867a-963f4427db34">

2024-04-18 02:36 UTC, m-Ryan requested changes

2024-04-18 07:27 UTC, alexmateos commented on packages/easy-email-extensions/src/AttributePanel/components/attributes/Link.tsx
>  import { IconLink } from '@arco-design/web-react/icon';
Sorry, messed up with the copy paste. Fixed it!

2024-04-18 14:14 UTC, m-Ryan approved these changes

2024-04-18 14:14 UTC, merged

2024-04-18 14:20 UTC, m-Ryan commented
@alexmateos  released,  please update to th latest version
 - easy-email-core@4.16.0
 - easy-email-editor@4.16.0
 - easy-email-extensions@4.16.0

2024-04-18 14:26 UTC, alexmateos commented
<img width="1200" alt="image" src="https://github.com/zalify/easy-email-editor/assets/5480073/0eb23c56-f466-4c3a-904f-69304ec29ff4">

Your builds are failing since you added pnpm. Actually it fails in local if you dont install pnpm.

You should check that out

2024-04-19 02:27 UTC, m-Ryan commented
The test has been fixed

2025-07-09 08:57 UTC, veenakrishnan01 commented
![Screenshot 2025-07-09 142937](https://github.com/user-attachments/assets/650f4342-a7fc-48d2-a6ce-397019c5ad13)
How can I add merge tags in the social link URL, similar to the icon URL? I want to be able to select a merge tag for the link!